server:
  port: 8081

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_rWeQ1VScX
#          wk-set-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_rWeQ1VScX/.well-known/jwks.json


logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
    web: TRACE

com:
  c4-soft:
    springaddons:
      security:
        issuers[0]:
          location: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_rWeQ1VScX
          authorities:
            claims: cognito:groups
        permit-all:
